-- ====================================================================
-- SCRIPT DE CRIAÇÃO DAS TABELAS NO SUPABASE (SISTEMA CRISMA - FASE 2)
-- Execute estes comandos no SQL Editor do seu projeto no Supabase:
-- https://supabase.com/dashboard/project/_/sql
-- ====================================================================

-- 1. TABELA DE DESPESAS (GASTOS DA CRISMA)
CREATE TABLE IF NOT EXISTS despesas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descricao TEXT NOT NULL,
    categoria TEXT NOT NULL, -- 'Material Didático', 'Alimentação / Lanche', 'Liturgia e Eventos', 'Outros Gastos'
    valor NUMERIC(10,2) NOT NULL,
    data_despesa DATE NOT NULL DEFAULT CURRENT_DATE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. TABELA DE ENTRADAS EXTRAS (RECEITAS E TAXAS AVULSAS)
CREATE TABLE IF NOT EXISTS entradas_extras (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descricao TEXT NOT NULL,
    origem TEXT NOT NULL, -- 'Taxa Extra', 'Doação', 'Oferta Avulsa', 'Inscrição Retiro'
    valor NUMERIC(10,2) NOT NULL,
    data_entrada DATE NOT NULL DEFAULT CURRENT_DATE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. TABELA DE ENCONTROS (CHAMADA DE FREQUÊNCIA)
CREATE TABLE IF NOT EXISTS encontros (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_encontro DATE NOT NULL UNIQUE,
    tema TEXT,
    observacao TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. TABELA DE PRESENÇAS / FALTAS DOS CRISMANDOS
CREATE TABLE IF NOT EXISTS presencas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    encontro_id BIGINT REFERENCES encontros(id) ON DELETE CASCADE,
    crismando_id BIGINT REFERENCES crismandos(id) ON DELETE CASCADE,
    status TEXT NOT NULL CHECK (status IN ('PRESENTE', 'FALTA', 'JUSTIFICADO')),
    observacao TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(encontro_id, crismando_id)
);

-- ====================================================================
-- CONFIGURAÇÃO DE PERMISSÕES / RLS (DESABILITAR RLS PARA ACESSO DIRETO VIA SDK ANON)
-- ====================================================================
ALTER TABLE despesas DISABLE ROW LEVEL SECURITY;
ALTER TABLE entradas_extras DISABLE ROW LEVEL SECURITY;
ALTER TABLE encontros DISABLE ROW LEVEL SECURITY;
ALTER TABLE presencas DISABLE ROW LEVEL SECURITY;

GRANT ALL ON TABLE despesas TO anon, authenticated, service_role;
GRANT ALL ON TABLE entradas_extras TO anon, authenticated, service_role;
GRANT ALL ON TABLE encontros TO anon, authenticated, service_role;
GRANT ALL ON TABLE presencas TO anon, authenticated, service_role;
